version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project-management-backend
    ports:
      - "8010:8010"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - BACKEND_PORT=8010
      - BACKEND_HOST=0.0.0.0
      - CORS_ORIGINS=http://18.234.41.103:3000,http://localhost:3000
    env_file:
      - .env
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - project-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project-management-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://18.234.41.103:8010
    env_file:
      - .env
    networks:
      - project-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  project-network:
    driver: bridge

volumes:
  logs:
    driver: local
